# Generated by Django 5.1.1 on 2024-09-17 03:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_craft_delete_crafts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craft',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
