# Generated by Django 5.1.1 on 2024-09-17 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_craft_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craft',
            name='description',
        ),
    ]
