# Generated by Django 5.1.1 on 2024-09-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_craft_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='craft',
            name='description',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
