# Generated by Django 5.1.1 on 2024-10-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_craft_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='craft',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
